#!/usr/bin/env sh

# this script downloads the given youtube link in youtube-dl
# download folder: $HOME/youtube/video & $HOME/youtube/audio
# formats: 360p, 480p, 720p, opus(audio)
# dependencies: dmenu, youtube-dl, aria2c

case "$(printf '360p\n480p\n720p\nopus' | dmenu -i -p 'Download format:')" in
  360p)
    youtube-dl '$1' -o '~/youtube/video/%(title)s.%(ext)s' -f 'bestvideo[ext=webm][height<=?360][fps<=?30][vcodec=?vp9]+bestaudio[ext=webm]'  --external-downloader aria2c
    exit 0;;
  480p)
    youtube-dl '$1' -o '~/youtube/video/%(title)s.%(ext)s' -f 'bestvideo[ext=webm][height<=?480][fps<=?30][vcodec=?vp9]+bestaudio[ext=webm]'  --external-downloader aria2c
    exit 0;;
  720p)
    youtube-dl '$1' -o '~/youtube/video/%(title)s.%(ext)s' -f 'bestvideo[ext=webm][height<=?720][fps<=?30][vcodec=?vp9]+bestaudio[ext=webm]'  --external-downloader aria2c
    exit 0;;
  opus)
    youtube-dl '$1' -o '~/youtube/audio/%(title)s.%(ext)s' -f 'bestaudio' --external-downloader aria2c
    exit 0;;
esac
